"""create ai sessions and messages

Revision ID: a4ccd284f5b2
Revises: a1c4e7f9b203
Create Date: 2026-07-22 14:47:16.568689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4ccd284f5b2'
down_revision: Union[str, Sequence[str], None] = 'a1c4e7f9b203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_sessions',
    sa.Column('session_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('category', sa.String(length=150), nullable=True),
    sa.Column('subcategory', sa.String(length=150), nullable=True),
    sa.Column('priority', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('resolution_status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("priority IN ('low', 'medium', 'high', 'critical')", name='ck_ai_sessions_priority'),
    sa.CheckConstraint("resolution_status IS NULL OR resolution_status IN ('resolved', 'unresolved')", name='ck_ai_sessions_resolution_status'),
    sa.CheckConstraint("status IN ('pending', 'processing', 'completed', 'failed')", name='ck_ai_sessions_status'),
    sa.CheckConstraint('confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1)', name='ck_ai_sessions_confidence_score_range'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index('ix_ai_sessions_account_created', 'ai_sessions', ['account_id', 'created_at'], unique=False)
    op.create_index('ix_ai_sessions_status_created', 'ai_sessions', ['status', 'created_at'], unique=False)
    op.create_table('ai_messages',
    sa.Column('message_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('sender_type', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("sender_type IN ('user', 'assistant', 'system')", name='ck_ai_messages_sender_type'),
    sa.ForeignKeyConstraint(['session_id'], ['ai_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index('ix_ai_messages_session_created', 'ai_messages', ['session_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_messages_session_created', table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_index('ix_ai_sessions_status_created', table_name='ai_sessions')
    op.drop_index('ix_ai_sessions_account_created', table_name='ai_sessions')
    op.drop_table('ai_sessions')
    # ### end Alembic commands ###
